# Generated by Django 3.0.1 on 2020-12-12 21:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=2)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='fleet/static/fleet/')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Format: '+1234567890', 9-10 digits allowed.", regex='^\\+?1?\\d{9,10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('call_sign', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBagAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Bag')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.Vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle-Bag Association',
                'verbose_name_plural': 'Vehicle-Bag Association',
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='bags',
            field=models.ManyToManyField(through='fleet.VehicleBagAssociation', to='inventory.Bag'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.Station'),
        ),
    ]
