# Generated by Django 3.1.4 on 2021-01-02 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20201226_0119'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VehicleBagAssociation',
            new_name='VehicleToBagAssociation',
        ),
    ]
