# Generated by Django 3.1.4 on 2021-01-02 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_auto_20210102_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicletobagassociation',
            options={'verbose_name': 'Vehicle to Bag Association'},
        ),
    ]
