# Generated by Django 3.2.15 on 2022-10-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_auto_20210102_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='fleet/'),
        ),
    ]
