# Generated by Django 3.2.15 on 2022-12-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_remove_station_station_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
