# Generated by Django 3.2.15 on 2022-12-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_station_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
