# Generated by Django 2.2.6 on 2020-12-24 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_compartment_bag'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagCompartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('brand', models.CharField(blank=True, max_length=40, null=True)),
                ('ordering', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Bag')),
                ('items', models.ManyToManyField(to='inventory.Item')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KitCompartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('brand', models.CharField(blank=True, max_length=40, null=True)),
                ('ordering', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('items', models.ManyToManyField(to='inventory.Item')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='kit',
            name='items',
            field=models.ManyToManyField(to='inventory.Item'),
        ),
        migrations.DeleteModel(
            name='Compartment',
        ),
        migrations.AddField(
            model_name='kitcompartment',
            name='kit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Kit'),
        ),
        migrations.AddField(
            model_name='kit',
            name='bag_compartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.BagCompartment'),
        ),
    ]
