# Generated by Django 2.2.6 on 2020-12-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20201224_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bagcompartment',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.Item'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.Item'),
        ),
        migrations.AlterField(
            model_name='kitcompartment',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.Item'),
        ),
    ]
