# Generated by Django 3.1.4 on 2020-12-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20201224_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bag',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bagcompartment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kitcompartment',
            options={},
        ),
        migrations.RemoveField(
            model_name='bagcompartment',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='kitcompartment',
            name='brand',
        ),
    ]
