# Generated by Django 3.1.4 on 2020-12-26 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20201225_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bagcompartmenttoitemassociation',
            options={'verbose_name': 'Bag Compartment to Item Association'},
        ),
        migrations.AlterModelOptions(
            name='kitcompartmenttoitemassociation',
            options={'verbose_name': 'Kit Compartment to Item Association'},
        ),
        migrations.AlterModelOptions(
            name='kittoitemassociation',
            options={'verbose_name': 'Kit to Item Association'},
        ),
    ]
