# Generated by Django 3.1.4 on 2021-01-03 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_bagorder_itemtobagorderassociation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagOrderToItemAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('bag_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.bagorder')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
            options={
                'verbose_name': 'Bag Order To Item Association',
            },
        ),
        migrations.DeleteModel(
            name='ItemToBagOrderAssociation',
        ),
    ]
