# Generated by Django 3.1.4 on 2021-01-03 21:23

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('inventory', '0010_auto_20210103_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleordertoitemassociation',
            old_name='bag_order',
            new_name='vehicle_order',
        ),
    ]
