# Generated by Django 3.1.4 on 2021-01-03 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20210103_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleorder',
            name='bag',
        ),
        migrations.AddField(
            model_name='vehicleordertoitemassociation',
            name='bag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.bag'),
        ),
    ]
