# Generated by Django 3.1.4 on 2021-01-08 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_auto_20210102_0346'),
        ('inventory', '0013_auto_20210108_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationorder',
            name='station_id',
        ),
        migrations.AddField(
            model_name='stationorder',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.station'),
        ),
    ]
